name: ddomfrontend  # Environment name

dependencies:  # Packages should be installed through conda if possible
  - python=3.11  # Python version
  - pre-commit
  - ruff
  - pyyaml
  - urllib3
  - requests
  - pypdf
  - pip
  - pip:  # Install additional packages through pip if they're not available in the default conda channel
    - elabapi_python
    - pubchempy
    - tkcalendar
    - rdkit